### Register user data
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
	"name": "Jonatha",
	"surname": "Lima",
    "cpf": "05616926370",
    "phone": "11985904599",
    "account": {
        "role": "user",
        "email": "jonathalimax@gmail.com",
        "password": "321pass"
    }
}

### Register user address
PUT http://localhost:8080/api/user/5dad1589983a37471c9e1ee5/signup/address
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvbmF0aGFsaW1heEBnbWFpbC5jb20iLCJpYXQiOjE1NzE3NTA4MjksImV4cCI6MTU3MTc1MTgyOX0.AoNcIGtNR1f0d8E_nv3GpAJM2i6m9Wf-qIyXDNec710

{
	"address": {
		"cep": "05847500",
        "country": "Brasil",
        "state": "SP",
        "city": "São Paulo",
        "neighbourhood": "Jardim Casablanca",
        "street": "Filpe Neri Teixeira",
        "number": "200",
        "complement": "Apt 102"
	}
}