### Send SMS
POST http://localhost:8080/api/account/sms
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvbmF0aGFsaW1heEBnbWFpbC5jb20iLCJpYXQiOjE1NzE3NTA4MjksImV4cCI6MTU3MTc1MTgyOX0.AoNcIGtNR1f0d8E_nv3GpAJM2i6m9Wf-qIyXDNec710
{
    "userId": "5da29c4995123916c4245eee",
    "phone": "11985904599"
}

### Validate SMS
POST http://localhost:8080/api/account/sms/validate
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvbmF0aGFsaW1heEBnbWFpbC5jb20iLCJpYXQiOjE1NzE3NTA4MjksImV4cCI6MTU3MTc1MTgyOX0.AoNcIGtNR1f0d8E_nv3GpAJM2i6m9Wf-qIyXDNec710

{
    "userId": "5da29c4995123916c4245eee",
    "verificationCode": "6852"
}