### Register establishment data
POST http://localhost:8080/api/establishment/signup
Content-Type: application/json

{
	"name": "Class Studio",
    "cnpj": "94030974000161",
    "phone": "23456532",
    "account": {
        "role": "admin_establishment",
        "email": "class@studio.com",
        "password": "123456"
    },
    "address": {
		"cep": "05847500",
        "country": "Brasil",
        "state": "SP",
        "city": "São Paulo",
        "neighbourhood": "Jardim Casablanca",
        "street": "Filpe Neri Teixeira",
        "number": "200",
        "complement": "Apt 102"
	}
}


### Establishment login
POST http://localhost:8080/api/establishment/login
Content-Type: application/json

{
	"email": "class@studio.com",
    "password": "123456"
}


### Register attendence address
POST http://localhost:8080/api/establishment/address
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsYXNzQHN0dWRpby5jb20iLCJpYXQiOjE1NzMwMDU2MTEsImV4cCI6MTU3MzAwNjYxMX0.Mu4x9ILiVCtwdgzV4JUvYjmbGmRbeK2OHBTNRLPXXy0
user-id: 5dbf07914878501bc82e68bd

{
    "address": {
		"cep": "05847500",
        "country": "Brasil",
        "state": "SP",
        "city": "São Paulo",
        "neighbourhood": "Jardim Casablanca",
        "street": "Filpe Neri Teixeira",
        "number": "200",
        "complement": "Apt 102"
	}
}


### Get all establishments
GET http://localhost:8080/api/establishments/address
Content-Type: application/json
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsYXNzQHN0dWRpby5jb20iLCJpYXQiOjE1NzI4MTM4NzksImV4cCI6MTU3MjgxNDg3OX0.6b0w2_IH9L1sBEHRdmgmSmawDPCCuI80cn0izbBvb-c