### Register user data
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
	"name": "Jonatha",
	"surname": "Lima",
    "cpf": "05616926370",
    "phone": "11985904599",
    "account": {
        "role": "user",
        "email": "jonathalimax@gmail.com",
        "password": "321pass"
    }
}

### Register user address
PUT http://localhost:8080/api/user/5dbdf639ca6aa12348e6c43e/signup/address
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvbmF0aGFsaW1heEBnbWFpbC5jb20iLCJpYXQiOjE1NzI3MzA0NTUsImV4cCI6MTU3MjczMTQ1NX0.ZxxZv34HtpDa6ATcbaD3WVbu2pK1n_nsZOxPF_U5AIw

{
	"address": {
		"cep": "05847500",
        "country": "Brasil",
        "state": "SP",
        "city": "São Paulo",
        "neighbourhood": "Jardim Casablanca",
        "street": "Filpe Neri Teixeira",
        "number": "200",
        "complement": "Apt 102"
	}
}

### Register establishment data
POST http://localhost:8080/api/establishment/signup
Content-Type: application/json

{
	"name": "Class Studio",
    "cnpj": "94030974000161",
    "phone": "23456532",
    "account": {
        "role": "admin_establishment",
        "email": "class@studio.com",
        "password": "123456"
    },
    "address": {
		"cep": "05847500",
        "country": "Brasil",
        "state": "SP",
        "city": "São Paulo",
        "neighbourhood": "Jardim Casablanca",
        "street": "Filpe Neri Teixeira",
        "number": "200",
        "complement": "Apt 102"
	}
}